name: metia
description: "A new Flutter project."

version: 1.0.25

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  app_links: ^6.4.0
  win32_registry: ^1.0.3
  url_launcher: ^6.1.7
  isar: 3.1.0+1
  isar_flutter_libs:
    git: 
      url: https://github.com/moaadhzair/isar_flutter_libs.git
  path_provider: ^2.1.5
  cached_network_image: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: 3.1.0+1
  build_runner: any


flutter:
  assets:
    - assets/icons/logo.svg
  uses-material-design: true
  
